export const categoryColors: { [key: string]: string } = {
  "Medical Expenses": "#FF6347", 
  Transportation: "#4682B4", 
  Entertainment: "#FFD700", 
  Gifts: "#FF69B4", 
  Education: "#32CD32", 
  Travel: "#8A2BE2", 
  "Rent/Mortgage": "#FF4500", 
  "Utilities - Water": "#00CED1", 
  "Utilities - Electricity": "#FFA500",
  Salary: "#6B8E23", 
  "Business Income": "#DAA520", 
  "Freelance Work": "#6495ED",
  "Festival Bonuses": "#DB7093", 
  "Gifts Received": "#FFDEAD", 
  "Rental Income": "#8B4513",  
  "Stock Dividends": "#20B2AA", 
  Royalties: "#778899", 
  Default: "#D3D3D3", 
};

export const categoryEmojies: { [key: string]: string } = {
  "Medical Expenses": "💉",
  "Transportation": "🚗",
  "Entertainment": "🎉",
  "Gifts": "🎁",
  "Education": "📚",
  "Travel": "✈️",
  "Rent/Mortgage": "🏠",
  "Utilities - Water": "💧",
  "Utilities - Electricity": "💡",
  "Salary": "💰",
  "Business Income": "📈",
  "Freelance Work": "💻",
  "Festival Bonuses": "🎊",
  "Gifts Received": "🎁",
  "Rental Income": "🏘️",
  "Stock Dividends": "📊",
  "Royalties": "👑",
  "Default": "🫰🏼"
};
